specVersion: 0.0.8
schema:
  file: ./schema.graphql
{{ #graftEnabled }}
features:
  - grafting
graft:
  base: {{ subgraphId }} # Subgraph ID of base subgraph
  block: {{ graftStartBlock }} # Block number
{{ /graftEnabled }}
dataSources:
  {{ #Vaults }}
  - kind: ethereum
    network: {{ network }}
    name: {{ name }}
    source:
      address: "{{ address }}"
      abi: Vault
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: Vault
          file: ./abis/Vault.json
        - name: VaultV2
          file: ./abis/VaultV2.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Deposit(indexed address,indexed address,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed address,uint256)
          handler: handleWithdraw
        - event: Harvest(indexed address,uint256)
          handler: handleHarvest
      file: ./src/mappings/vaultMappings.ts
  {{ /Vaults }}
  
  {{ #V2Vaults }}
  - kind: ethereum
    network: {{ network }}
    name: {{ name }}
    source:
      address: "{{ address }}"
      abi: VaultV2
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: VaultV2
          file: ./abis/VaultV2.json
        - name: Vault
          file: ./abis/Vault.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: Harvest(indexed address,uint256)
          handler: handleHarvest
      file: ./src/mappings/vaultV2Mappings.ts
  {{ /V2Vaults }}