specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: rocket-pool
    network: mainnet
    source:
      address: '0x3bDC69C4E5e13E52A65f5583c23EFB9636b469d6'
      abi: RocketVault
      startBlock: 13325238
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Token
        - Pool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        ###########################################
        ######## RocketPool Generic ABIs ##########
        ###########################################
        - name: DepositPool
          file: ./abis/depositpool.json
        - name: RocketStorage
          file: ./abis/rocketStorage.json
        - name: RocketVault
          file: ./abis/rocketVault.json
        - name: RETH
          file: ./abis/reth.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: EtherDeposited(indexed string,uint256,uint256)
          handler: handleEtherDeposit
        - event: EtherWithdrawn(indexed string,uint256,uint256)
          handler: handleEtherWithdrawn
      file: ./src/mappings/RocketPool.ts
