specVersion: 0.0.8
schema:
  file: ./schema.graphql
{{#graftEnabled}}
features:
  - grafting
graft:
  base: {{ subgraphId }} # Subgraph ID of base subgraph
  block: {{ graftStartBlock }} # Block number
{{/graftEnabled}}
dataSources:
  {{ #RestakeManager }}
  - kind: ethereum
    network: {{ network }}
    name: RestakeManager
    source:
      address: "{{ RestakeManager.address }}"
      abi: RestakeManager
      startBlock: {{ RestakeManager.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: RestakeManager
          file: ./abis/RestakeManager.json
        - name: DepositQueue
          file: ./abis/DepositQueue.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Deposit(address,address,uint256,uint256,uint256)
          handler: handleDeposit
        - event: UserWithdrawCompleted(bytes32,address,address,uint256,uint256)
          handler: handleUserWithdrawCompleted
      file: ./src/mappings/restakeManagerMappings.ts
  {{ /RestakeManager }}

  {{ #DepositQueue }}
  - kind: ethereum
    network: {{ network }}
    name: DepositQueue
    source:
      address: "{{ DepositQueue.address }}"
      abi: DepositQueue
      startBlock: {{ DepositQueue.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: DepositQueue
          file: ./abis/DepositQueue.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: RewardsDeposited(address,uint256)
          handler: handleRewardsDeposited
        - event: ProtocolFeesPaid(address,uint256,address)
          handler: handleProtocolFeesPaid
      file: ./src/mappings/depositQueueMappings.ts
  {{ /DepositQueue }}

  {{ #ezETH }}
  - kind: ethereum
    network: {{ network }}
    name: ezETH
    source:
      address: "{{ ezETH.address }}"
      abi: ezETH
      startBlock: {{ ezETH.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: ezETH
          file: ./abis/EZETH.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      callHandlers:
        - function: mint(address,uint256)
          handler: handleMint
        - function: burn(address,uint256)
          handler: handleBurn
      file: ./src/mappings/ezEthMappings.ts
  {{ /ezETH }}
