specVersion: 0.0.4
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: Comptroller
    network: {{ network }}
    source:
      address: "{{ factoryAddress }}"
      abi: Comptroller
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./protocols/compound-v2/src/mapping.ts
      entities:
        - LendingProtocol
        - Market
        - Token
      abis:
        - name: Comptroller
          file: ./abis/Comptroller.json
        - name: CToken
          file: ./abis/CToken.json
        - name: PriceOracle1
          file: ./abis/compound-v2/PriceOracle1.json
        - name: PriceOracle2
          file: ./abis/compound-v2/PriceOracle2.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/compound-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/compound-v2/ERC20NameBytes.json
      eventHandlers:
        - event: MarketListed(address)
          handler: handleMarketListed
        - event: MarketEntered(address,address)
          handler: handleMarketEntered
        - event: MarketExited(address,address)
          handler: handleMarketExited
        - event: NewCollateralFactor(address,uint256,uint256)
          handler: handleNewCollateralFactor
        - event: NewLiquidationIncentive(uint256,uint256)
          handler: handleNewLiquidationIncentive
        - event: NewPriceOracle(address,address)
          handler: handleNewPriceOracle
        - event: ActionPaused(address,string,bool)
          handler: handleActionPaused
templates:
  - name: CToken
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: CToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./protocols/compound-v2/src/mapping.ts
      entities:
        - Event
        - Market
        - UsageMetricsDailySnapshot
        - FinancialsDailySnapshot
        - MarketDailySnapshot
      abis:
        - name: Comptroller
          file: ./abis/Comptroller.json
        - name: PriceOracle1
          file: ./abis/compound-v2/PriceOracle1.json
        - name: PriceOracle2
          file: ./abis/compound-v2/PriceOracle2.json
        - name: PriceOracle
          file: ./abis/PriceOracle.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: CToken
          file: ./abis/CToken.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: Mint(address,uint256,uint256)
          handler: handleMint
        - event: Redeem(address,uint256,uint256)
          handler: handleRedeem
        - event: Borrow(address,uint256,uint256,uint256)
          handler: handleBorrow
        - event: RepayBorrow(address,address,uint256,uint256,uint256)
          handler: handleRepayBorrow
        - event: LiquidateBorrow(address,address,uint256,address,uint256)
          handler: handleLiquidateBorrow
        - event: NewReserveFactor(uint256,uint256)
          handler: handleNewReserveFactor
        - event: AccrueInterest(uint256,uint256,uint256,uint256)
          handler: handleAccrueInterestNew
  - name: CTokenOld
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: CTokenOld
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./protocols/compound-v2/src/mapping.ts
      entities:
        - Event
        - Market
        - UsageMetricsDailySnapshot
        - FinancialsDailySnapshot
        - MarketDailySnapshot
      abis:
        - name: Comptroller
          file: ./abis/Comptroller.json
        - name: CTokenOld
          file: ./abis/compound-v2/CTokenOld.json
        - name: PriceOracle1
          file: ./abis/compound-v2/PriceOracle1.json
        - name: PriceOracle2
          file: ./abis/compound-v2/PriceOracle2.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: CToken
          file: ./abis/CToken.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: AccrueInterest(uint256,uint256,uint256)
          handler: handleAccrueInterestOld
