on: 
  push:

jobs:
  Deployment: 
    runs-on: ubuntu-latest
    steps: 
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true

      - uses: actions/checkout@v2
      - uses: steegecs/Subgraph-Build-Checker@test
        with: 
          CHANGED_FILES: "${{ steps.files.outputs.all }}"
          ABSOLUTE_PATH: ${{ github.workspace }}
          GRAPH_DEPLOYMENT_LOCATION: steegecs
          